### ISSUE TITLE
where are all models, include yolov3?

### ISSUE THREAD

**Issue by wac81** [Avocadrew/AutoBilliards#1]
where are all models to download? include yolov3.

**Comment by Avocadrew** [comment]
We cannot release the model due to some restrictions. On the other hand, I've just uploaded the code for training and output of the final version, hope it would help! You can find the code we used during our methodology trials and numerous tools on Image Processing that you may find helpful for your particular scenario at https://github.com/Yi-Jun-Wang/EEproject
